### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by vasilishunter** [TheNewHEROBRINEX/AutoCreative#1]

**Comment by TheNewHEROBRINEX** [comment]
This plugins enables creative mode in one specific world of the server. Set the world in the config.yml and restart the server.

**Comment by TheNewHEROBRINEX** [comment]
Do you understand now?

**Comment by vasilishunter** [comment]
I did all that yet while the plugin loads perfectly the world that I set is still in survival

**Comment by TheNewHEROBRINEX** [comment]
Operators are exempt from the plugin by default so to test the plugin you should deop yourself or negate the autocreative.exempt permission.

**Comment by vasilishunter** [comment]
It worked thank you.🙏
